# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LTY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CleanJSON'
  pod 'CollectionKit'
  pod 'EachNavigationBar'
  pod 'SnapKit'
  pod 'Toast-Swift'
  pod 'IQKeyboardManagerSwift'
  pod 'MJRefresh'
  # Pods for LTY

  target 'LTYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LTYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
